### ISSUE TITLE
about_snap.md should be renamed to README.md

### ISSUE THREAD

**Issue by towerofnix** [jmoenig/AboutSnap#2]
...So that it is embedded right onto the homepage of this repository.

**Comment by jmoenig** [comment]
good point, @towerofnix , but I was planning to write an explicit readme and to include a CC license because we might break up the about page into several smaller ones, and add others. Thanks!

**Comment by jmoenig** [comment]
... OTOH, you're absolutely right, Florrie. I'm going to do that right now. GREAT point, thank you!

**Comment by jmoenig** [comment]
Oh, while we're at it: Feel free to contribute whatever you feel should be mentioned. We're trying to make a website that will be hosted at snap.sap.com and link to our (snap.berkeley.edu) page but with information for people who are not yet in our community. You know, corporate folk and such ;-)

**Comment by towerofnix** [comment]
Coolio! This is definitely a neat little readme and it'll be really useful to a lot of folx! :D
