### ISSUE TITLE
Nit - should the "Snap! is Scheme disguised as Scratch" text be a quote or not?

### ISSUE THREAD

**Issue by towerofnix** [jmoenig/AboutSnap#3]
Evil nitpick here, just spitballing a thought! :)

Should *"Snap! is Scheme disguised as Scratch"* be a quote or not? It doesn't exactly feel like it's *truly* a quotation since bh is, of course, right there on the Snap<i>!</i> team; and the phrase has always seemed to me more like a slogan than a, say, review from a famous computer scientist! :P

**Comment by jmoenig** [comment]
Haha! Well, you know, to me @brianharvey *is* a famous computer scientist and I've always loved his ... totally partial ... (slogan) assessment, so I quote Brian everywhere they let me :-)
Mind you, the bigger issue is that nowadays only very few people - even CS teachers and professors - have heard of Scheme. We'll let Brian decide on this...

**Comment by brianharvey** [comment]
I think this is a case where a compromise works.  Have the quote, but label it "Snap<i>!</i> co-developer Brian Harvey" so people don't think we're trying to make me seem like a random user.

**Comment by towerofnix** [comment]
Resolved in 6e9bb6a232a36e88ef547b194822b35ae5bed406!
